# Название воркфлоу. Выбирайте на свой вкус
name: "automate-all-the-things"

# Триггеры ( = условия), при которых воркфлоу сработает
# В данном случае: на каждый пуш в ветку main
on:
  push:
    branches:
      - 'main'

# Задачи, которые будут выполняться в рамках флоу
jobs:
  # Название задачи, которое будет отображаться в GitHub
  build_and_push:
    # На каком виртуальном сервере будет выполняться задача
    # В данном случае, на свежайшей версии Ubuntu. Неплохой выбор.
    runs-on: ubuntu-latest
    # Шаги выполнения задачи (о них ниже по тексту)
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Те самые "секреты" из настроек репозитория
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          # С каким тегом будет загружен образ
          # Переменные тоже поддерживаются
          tags: darkweid/test-docker-push:latest